packaging_format = 2

id = "hub"
name = "HUB HSD"
description.en = "Open teaching and learning materials of HSD and cooperation partners."
description.de = "Offene Lehr- und Lernmaterialien der HSD und Kooperationspartner*innen"

version = "4.1.6~ynh1"

maintainers = [""]

[upstream]
license = "GPL-3.0-or-later"
website = "https://hub.hs-duesseldorf.de"
admindoc = "https://docs.moodle.org/401/en/Main_page"
code = "https://github.com/moodle/moodle"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = true
sso = true
disk = "50M"
ram.build = "2000M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/mdl"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.site_name]
    ask.en = "Choose a name for the site you want to create"
    ask.fr = "Choisissez un nom pour le site que vous voulez créer"
    ask.de = "Wählen Sie einen Namen für den HUB
    type = "string"
    default = "hub"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://packaging.moodle.org/stable401/moodle-latest-401.tgz"
        sha256 ="351c414e235a86cb0f70d6b1d0153fcd77513eea988dd87571a1bf5865c95b7d"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "composer postgresql php8.0-apcu php8.0-common php8.0-mbstring php8.0-curl php8.0-xmlrpc php8.0-soap php8.0-zip php8.0-gd php8.0-xml php8.0-intl php8.0-pgsql php8.0-ldap php8.0-memcached php8.0-mongodb php8.0-yaml php8.0-redis php8.0-imagick"

    [resources.database]
    type = "postgresql"
